package com.victor.multiUtilityToolkit.jms.constants;

public class JMSConstants {
	public static final String JMS_SERVER_FILE_PATH = "C://serverConfig.txt";
	public static final String JMS_MESSAGE_ID = "JMSMessageID";
	public static final String EQUALS = "=";
	public static final String SINGLE_QUOTE = "'";
	public static final String COLON = ":"; 
	public static final String SPACE = " ";
	public static final String UNDER_SCORE = "_";
	public static final String MESSAGES_TEXT = "Messages_";
	public static final String EXTN_ZIP = ".zip";
	public static final String EXTN_XML = ".xml";
	public static final String LINE_SEP = "line.separator";
	public static final String JMS_TIME_STAMP = "JMSTimestamp";
	public static final String JMS_CORRELATION_ID = "JMSCorrelationID";
	public static final String JMS_DELIVERY_MODE = "JMSDeliveryMode";
	public static final String JMS_DESTINATION = "JMSDestination";
	public static final String JMS_EXPIRATION = "JMSExpiration";
	public static final String JMS_PRIORITY = "JMSPriority";
	public static final String JMS_REDELIVERED = "JMSRedelivered";
	public static final String JMS_REPLY_TO = "JMSReplyTo";
	public static final String JMS_TYPE = "JMSType";
	public static final String S_NO = "Serial No";
	public static final String HEADER = "Header";
	public static final String VALUE = "Value";
	public static final String EMPTY_STRING = "";
	public static final String DATE_PATTERN_1 = "dd-MMM-yyyy";
	public static final String BETWEEN = "BETWEEN";
	public static final String AND = "AND";
	public static final String SUBMIT = "submit";
	public static final String FROM = "From";
	public static final String TO = "To";
	public static final String SAVE_ALL = "Save All"; 
	public static final String SAVE_AS = "Save As";
	public static final String GET_QUEUES = "GET QUEUES";
	public static final String GET_DESTINATIONS = "GET DESTINATIONS";
	public static final String DOUBLE_BACK_SLASH = "\\";
	public static final String SEND_DELETE = "Transaction";
	public static final String ADD_SERVER = "Add Server";
	public static final String SERVER_TEXT = "Server:         ";
	public static final String USER_TEXT = "User Id:       ";
	public static final String PASS_TEXT = "Password:   ";
	public static final String QUEUE_TEXT = "Queues:  ";
	public static final String SELECTOR_TEXT = "Selector:  ";
	public static final String STATUS_TEXT = "Status: ";
	public static final String SELECT_FILE_TEXT = "Select File";
	public static final String SEND_TEXT = "Send";
	public static final String DELETE_TEXT = "Delete";
	public static final String SERVER_NAME_TEXT = "Server Name: ";
	public static final String BROWSE = "Browse";	
	public static final String BROWSE_ENTIRE_QUEUE = "BROWSE ENTIRE QUEUE";
	public static final String BROWSE_USING_SELECTOR = "BROWSE USING SELECTOR";
	public static final String TOOLKIT_IMAGE_PATH = "/images/multiutiltoolkitheader2.JPG";
	public static final String TOOLKIT_TEXT = "Multi Utility Toolkit";
	public static final String JMS_MODULES = "JMS Modules";
}
