package com.victor.importer.supportMethods;

public class ColumnDataTypes {
	public static final String SQL_SERVER_BIGINT = "bigint";
	public static final String SQL_SERVER_TIME = "time";
	public static final String SQL_SERVER_INT = "int";
	public static final String SQL_SERVER_SMALLINT = "smallint";
	public static final String SQL_SERVER_TINYINT = "tinyint";
	public static final String SQL_SERVER_BIT = "bit";
	public static final String SQL_SERVER_DECIMAL = "decimal";
	public static final String SQL_SERVER_NUMERIC = "numeric";
	public static final String SQL_SERVER_MONEY = "money";
	public static final String SQL_SERVER_SMALLMONEY = "smallmoney";
	public static final String SQL_SERVER_DATETIME = "datetime";
	public static final String SQL_SERVER_DATE = "date";
	public static final String SQL_SERVER_SMALLDATETIME = "smalldatetime";
	public static final String SQL_SERVER_TIMESTAMP = "timestamp";
	public static final String SQL_SERVER_CHAR = "char";
	public static final String SQL_SERVER_VARCHAR = "varchar";	
	public static final String SQL_SERVER_NCHAR = "nchar";
	public static final String SQL_SERVER_NVARCHAR = "nvarchar";
	public static final String SQL_SERVER_TEXT = "text";
	public static final String SQL_SERVER_NTEXT = "ntext";
	public static final String SQL_SERVER_BINARY = "binary";
	public static final String SQL_SERVER_VARBINARY = "varbinary";
	public static final String SQL_SERVER_IMAGE = "image";
	public static final String SQL_SERVER_UNIQUEIDENTIFIER = "uniqueidentifier";
	
	public static final String ORACLE_VARCHAR2 = "VARCHAR2";
	public static final String ORACLE_NVARCHAR2 = "NVARCHAR2";
	public static final String ORACLE_VARCHAR = "VARCHAR";
	public static final String ORACLE_CHAR = "CHAR";
	public static final String ORACLE_NCHAR = "NCHAR";
	public static final String ORACLE_NUMBER = "NUMBER";
	public static final String ORACLE_PLS_INTEGER = "PLS_INTEGER";
	public static final String ORACLE_BINARY_INTEGER = "BINARY_INTEGER";
	public static final String ORACLE_LONG = "LONG";
	public static final String ORACLE_DATE = "DATE";
	public static final String ORACLE_TIMESTAMP = "TIMESTAMP";
	public static final String ORACLE_RAW = "RAW";
	public static final String ORACLE_LONGRAW = "LONG RAW";
	public static final String ORACLE_ROWID = "ROWID";
	public static final String ORACLE_UROWID = "UROWID";
	public static final String ORACLE_MLSLABEL = "MLSLABEL";
	public static final String ORACLE_CLOB = "CLOB";
	public static final String ORACLE_NCLOB = "NCLOB";
	public static final String ORACLE_BLOB = "BLOB";
	public static final String ORACLE_BFILE = "BFILE";
	public static final String ORACLE_XMLTYPE = "XMLType";
}
